FROM oven/bun:latest

WORKDIR /app

# Install dependencies
COPY package.json .
RUN bun install

# Copy the rest of the application
COPY . .

# Expose the port
EXPOSE 3000

# Command to run the application
CMD ["bun", "run", "dev", "--host", "0.0.0.0"]