version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: yata_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/yata_dev
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - backend
    command: bun run dev --host 0.0.0.0

  mcp-yata:
    build:
      context: ./mcp-yata
      dockerfile: Dockerfile
    environment:
      - OAUTH_CLIENT_ID=${MCP_OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${MCP_OAUTH_CLIENT_SECRET}
      - OAUTH_TOKEN_URL=http://backend:8000/api/v1/oauth/token
      - API_BASE_URL=http://backend:8000/api/v1/oauth-todos
      - SERVER_NAME=mcp-yata
      - SERVER_VERSION=1.0.0
    depends_on:
      - backend
    command: python -m mcp_yata.server

volumes:
  postgres_data:
  redis_data: